apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cso-base-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/steven-matison/Cloudera-Streaming-Operators-ArcoCD'
    targetRevision: HEAD
    path: . 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true