apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cso-base-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Points to your specific Argo CD repo
    repoURL: 'https://github.com/steven-matison/Cloudera-Streaming-Operators-ArcoCD'
    targetRevision: HEAD
    path: base # Adjust this if your 'base' folder is under a different path
  destination:
    server: 'https://kubernetes.default.svc'
    # Base often handles multiple namespaces, but we target 'default' or 'argocd' for the root
    namespace: argocd 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true